language: python

# Enable container-based builds
sudo: false

# Enable PIP deps cache between builds
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - "pip install ."
  - "pip install nose"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"

# command to run tests
script: nosetests

notifications:
  email:
    - drslump@pollinimini.net
