language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# command to install dependencies
install:
  - "pip install ."
  - "pip install unittest2"  # Python 2.6 support
  - "pip install nose"

# command to run tests
script: nosetests
